---
# tasks file for docker
# Load vars specific to OS Family.
 - include_vars: "{{ ansible_os_family }}.yml"
   when: ansible_os_family != 'Debian'

 - include: RedHat.yml
   when: ansible_os_family == 'RedHat'

 - include: Debian.yml
   when: ansible_os_family == 'Debian'

 - include: service.yml

 - include: compose.yml
   when: compose
