---
 - name: update RedHat Systems
   yum: name=* state=latest

 - name: Install Docker
   shell: curl -sSL https://get.docker.io/ | sudo sh
   sudo: yes

 - group: name=docker state=present

 - name: Add User to the Docker Group
   command: usermod -aG docker "{{ RedHat_User }}"
