---
- hosts: digitalocean

  vars_prompt:
    - name: prefix
      prompt: "What is the prefix of the droplets?"
      private: no
    - name: number
      prompt: "How many droplets do you want to create?"
      private: no

  vars_files:
    - vars.yml
  
  tasks:

  - name: Launching {{ number  }} Droplets
    digital_ocean: >
      state=present
      command=droplet
      name={{ item }}
      unique_name=yes
      user_data={{ user_data }}
      size_id={{ size }}
      region_id={{ region }}
      image_id={{ image }}
      ssh_key_ids={{ ssh_id }}
      api_token={{ do_token }}
    with_sequence:
      start=1
      end={{ number }}
      format={{ prefix }}%02x
    register: droplet_details

  - debug: msg="IP is {{ item.droplet.ip_address }}"
    with_items: "{{ droplet_details.results }}"
